version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: postgres_local
    restart: unless-stopped
    environment:
      POSTGRES_USER: latifah4
      POSTGRES_PASSWORD: Gator4Life
      POSTGRES_DB: care_outreach
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U latifah4 -d care_outreach']
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7
    container_name: redis_local
    restart: unless-stopped
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata:
  redisdata:
